version: '3.9'
services:
  store_db:
    image: postgres:15
    container_name: store_db
    env_file:
      - .env # Asegúrate de que el archivo .env esté en el mismo nivel que tu docker-compose.yml
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  store_backend:
    container_name: store_backend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - store_db
    ports:
      - '8000:8000'
    env_file:
      - .env # Cargar el archivo .env con las variables de entorno
    command:
      [
        'uvicorn',
        'app.main:app',
        '--host',
        '${HOST}',
        '--port',
        '${PORT}',
        '--reload',
      ]
    volumes:
      - .:/code

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env # Cargar las variables de entorno para PgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - store_db

volumes:
  postgres_data:
